# Generated by Django 4.2.2 on 2023-07-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
